/* EDUCATION ATLAS — two knowledge bases authored for TUB's "How Heat Works" module
   (integration pending). Banks parallel-authored content so it isn't lost.
   - APPLIANCE_ATLAS : how each heat source/appliance works (science dumbed down,
                      what to expect, how to adjust), SA-localized.
   - FATS            : a "Fats & Oils" masterclass + a smoke-point reference table.
   SA-localized: °C / metric / braai / coriander. No emoji, no cups/oz/°F. */
window.APPLIANCE_ATLAS=[
{"id":"gas-hob","name":"Gas stovetop (hob)","heat":"Conduction from the pot + infrared radiation from the flame","simple":"The flame heats the metal pot directly and the pot conducts heat into the food. You also get radiant heat from the glowing flame, which helps brown things.","expect":"Instant heat response — flame changes immediately. Visible flame size tells you the power. Great for searing and wok cooking.","adjust":"Turn the dial — flame size changes instantly. For low heat use the smallest burner. Keep flames from licking up the pot sides.","best_for":"Wok cooking, searing, stir-frying, sautéing, sauces, boiling.","watch":"Flame can heat handles dangerously hot; uneven pans scorch.","sa":"Most SA kitchens run gas or electric hobs; gas is prized for curry and braai-side work."},
{"id":"electric-plate","name":"Electric plate / solid-plate stovetop","heat":"Conduction through the solid metal plate","simple":"Electricity heats a heavy cast-iron plate under the pot. The plate heats slowly and stays hot for ages, conducting heat through the pot bottom.","expect":"Very slow response — turn it down and heat lingers 10–15 min. Takes 5+ min to get hot. Cheap but frustrating for precise control.","adjust":"Preheat on high for 5 min. Turn down early — heat lingers. Lift the pot off to stop cooking instantly.","best_for":"Slow simmering, boiling water, long stews where quick changes aren't needed.","watch":"Poor precise control; hot spots develop over time.","sa":"Common in older SA flats — cheap and lasts forever. Load-shedding kills them instantly."},
{"id":"ceramic-hob","name":"Ceramic / radiant-glass stovetop","heat":"Conduction through glass + infrared from elements beneath","simple":"Elements under a smooth glass top glow red-hot. The glass conducts heat to the pot while infrared radiates through it into the metal.","expect":"Medium response — slower than gas, faster than solid plates. Smooth surface, easy to clean. Glass stays hot ~5 min after switch-off.","adjust":"Turn down 2 min before you want a drop. Use residual heat to finish or keep warm. Flat-bottomed pots only.","best_for":"Everyday cooking, easy cleaning, gentle simmering.","watch":"Glass scratches; spilled sugar burns into permanent marks; needs flat pots.","sa":"Common in newer SA kitchens — easy to wipe after making pap."},
{"id":"induction-hob","name":"Induction stovetop","heat":"Magnetic induction — the pot itself becomes the heat source","simple":"A magnetic field makes the iron in the pot heat up directly. The glass stays cool; only the pot gets hot. No heat transfer needed — the pot IS the element.","expect":"Instant response (as fast as gas), ~90% efficient, cool surface, unmatched control.","adjust":"Touch controls give precise power; boost for rapid boiling; lift the pot and heating stops instantly.","best_for":"Precision cooking, searing, boiling, temperature-sensitive sauces.","watch":"Needs ferrous pots (magnet must stick). Many non-stick pans don't work.","sa":"Most efficient hob — saves electricity; runs in load-shedding on a small inverter."},
{"id":"conventional-oven","name":"Conventional oven (static/thermal)","heat":"Natural convection — hot air rises, cool air sinks","simple":"Elements heat the air; hot air rises so the top runs hotter than the bottom. Food cooks surrounded by hot air.","expect":"Uneven heat (top browns faster), slow preheat (15–25 min), gentle baking.","adjust":"Rotate trays halfway; preheat fully; use the middle rack.","best_for":"Casseroles, roasts, fruit cakes, bread — forgiving bakes.","watch":"Hot spots are common; opening the door drops temperature fast.","sa":"Most SA ovens are this type. Learn your hot spots by baking bread."},
{"id":"convection-oven","name":"Fan-forced / convection oven","heat":"Forced convection — a fan circulates hot air evenly","simple":"A fan constantly blows hot air around the food, so temperature is even everywhere. Moving air strips the cool layer off the food so it cooks faster.","expect":"Even browning, ~20–25% quicker, crispier skin, shorter preheat, multi-tray even baking.","adjust":"Reduce temp by 20°C vs conventional (or keep temp, shorten time); don't overcrowd — air must flow.","best_for":"Crisp roasts, multi-tray baking, cookies, pizza.","watch":"Delicate bakes (meringue, soufflé) dry out faster; light items can blow around.","sa":"Essential for batch-baking vetkoek, koeksisters, malva for big families."},
{"id":"broiler","name":"Broiler (overhead grill element)","heat":"Infrared radiation — direct radiant heat from above","simple":"A fierce element glows red above the food. Infrared radiation browns the surface instantly while the air stays relatively cool.","expect":"Instant surface browning, char, crunch; thin tops cook before bottoms heat through; burns in seconds.","adjust":"Rack distance is your power control — closer is hotter; keep the door ajar to watch; flip halfway.","best_for":"Steaks, aubergine, cheese on toast, crème brûlée, finishing gratins.","watch":"Perfect to burnt in 15 seconds; thick items stay raw inside; smokes fast.","sa":"Called the 'oven grill' — perfect for finishing bobotie's golden custard crust."},
{"id":"charcoal-kettle-grill","name":"Charcoal/Gas kettle grill (Weber-style)","heat":"Convection + radiation (+ conduction via the grate)","simple":"Coals or a burner warm the air inside the closed kettle, circulating like a convection oven, while glowing coals radiate infrared to brown the surface. Contact with the grate adds conduction.","expect":"180–260°C; dark flavourful crust, smoke flavour from drips; more even than an open braai.","adjust":"Vents (more air = hotter); bank coals for indirect heat; lid closed = roast, open = grill.","best_for":"Large roasts (leg of lamb, chicken), ribs, pizza (with stone).","watch":"Fat drips cause flare-ups — keep a water spray handy; let coals ash over first.","sa":"A suburban SA staple — bridges traditional braai and modern convenience; great when the southeaster blows."},
{"id":"braai","name":"Braai (wood & coal open fire)","heat":"Radiation + convection from glowing coals and flame","simple":"Wood burns to hot coals that radiate intense infrared heat upward. Flames add instant char; rising hot air gives natural convection. Heat is fierce and uneven — closer = more sear.","expect":"250–400°C over coals; dark smoky crust, wood-smoke flavour; fast and social.","adjust":"Build fire in layers; cook over glowing embers, not angry flame; raise/lower the grid; fan coals to spike heat.","best_for":"Boerewors, lamb chops, steak, wings, sosaties, foil-wrapped fish, mielies.","watch":"Fat flare-ups char food; never use firelighters once food is on; wind blows ash.","sa":"SA's cultural heartbeat — a ritual of gathering. Family wood mixes: blue gum, rooikrans, sekelbos. Coals must be 'just right' — no flames, glowing embers."},
{"id":"boil-simmer","name":"Boil & simmer (water on a hob)","heat":"Conduction — heat through the pot into water, then into food","simple":"The stove heats the pot, which heats the water; warm water rises and cool sinks, mixing. Food absorbs heat by contact. Boil = violent bubbles at 100°C; simmer = gentle bubbles just under.","expect":"Boiling is fast but rough; simmering (80–95°C) is gentle and even; no browning — food stays pale and moist.","adjust":"Dial controls intensity; lid on speeds heating, off cools it; add cold water to stop a boil.","best_for":"Pasta, potatoes, rice, eggs, soups, stews, curries, blanching veg; simmer for oxtail, bredie, beans.","watch":"Starches boil over — watch and stir; at altitude (Joburg) water boils ~95°C so cooks take longer.","sa":"Every SA kitchen has pap on the simmer; the backbone of bredies and soups."},
{"id":"steaming","name":"Steaming (basket/insert)","heat":"Convection — hot steam carries heat to the food","simple":"Boiling water makes steam that rises around the food; when it touches cooler food it condenses, releasing heat. Constant steam cooks gently from all sides.","expect":"100°C but gentler than boiling; colours stay bright, nutrients stay in the food; no browning.","adjust":"Adjust heat under the water; keep the lid tight; top up with boiling water from a kettle; never boil dry.","best_for":"Vegetables, fish fillets, dumplings, steamed pudding, rice; reheating pap without drying.","watch":"Steam burns penetrate deep — open the lid away from your face; don't overcook.","sa":"Steamed veg alongside braaied meat and pap; township steamed breads and mielie bread."},
{"id":"microwave","name":"Microwave oven","heat":"Dielectric heating — waves agitate water molecules inside the food","simple":"Microwaves penetrate food and make water molecules spin millions of times a second; that friction creates heat, so food warms from within. Waves bounce off the metal walls to reach all parts.","expect":"Fast but uneven heating; moist areas heat first; no browning or crisping; food emerges hot but pale.","adjust":"Power level (100% fast, 50% gentle); start with less time and add; stir halfway; let stand 1–2 min to equalise.","best_for":"Reheating, melting butter/chocolate, steaming veg with a splash of water, defrosting, baked potatoes.","watch":"Superheated liquids can erupt — stir carefully; never run empty; no metal (arcing).","sa":"Essential for quick meals and reheating yesterday's pap; in load-shedding a generator-powered microwave keeps dinner moving."},
{"id":"air-fryer","name":"Air fryer","heat":"Fan-forced convection in a small chamber","simple":"A small fan oven circulating hot air fast; moving air strips the cool layer off food so heat reaches the surface quickly. Not actually frying — roasting with forced air.","expect":"Fast, crispy browned exterior, moist interior, 'fried' texture with far less oil; rapid preheat.","adjust":"160–200°C; shake the basket halfway; don't overcrowd; a light oil spray aids browning.","best_for":"Frozen chips, chicken pieces, burgers, veg, reheating, small crispy portions.","watch":"Overcrowding = steaming not frying; dry foods brown poorly; small capacity.","sa":"Great for slap chips, wings, wors patties, vetkoek with less oil than deep-frying."},
{"id":"pressure-cooker","name":"Pressure cooker (stovetop/electric)","heat":"Steam under pressure — water boils above 100°C in a sealed vessel","simple":"A sealed lid traps steam, raising pressure and pushing water's boiling point to ~120°C. Higher temperature means faster cooking; pressure forces moisture into tough fibres.","expect":"Soups/stews/curries in 15–30 min instead of hours; tough cuts turn fork-tender fast; flavours concentrate.","adjust":"Stovetop: high to pressure then low to maintain a hiss; electric: presets or manual; natural release for meat, quick for veg.","best_for":"Soups, stews, curry, oxtail, beef shin, beans, chickpeas, stocks.","watch":"Don't overfill (max two-thirds); foamy foods (split peas) can spurting; check seal and vent.","sa":"Ideal for oxtail, breyani, curry, bobotie, samp in a fraction of the time."},
{"id":"slow-cooker","name":"Slow cooker / crockpot","heat":"Low steady conduction from base and sides over many hours","simple":"Gentle moist heat simmers food slowly for hours, breaking down connective tissue in tough cuts without overcooking; little evaporation so liquids barely reduce.","expect":"Fall-off-the-bone tenderness, developed flavour, set-and-forget, one pot.","adjust":"Low (~85–95°C) 8–10 hr, High (~95–105°C) 4–6 hr; brown meat first; add dairy near the end.","best_for":"Tough cuts (brisket, pork shoulder), soups, stews, curries, pulled meat, beans.","watch":"Overfilling = uneven; dairy splits; veg go mushy; liquid won't reduce — reduce at the end.","sa":"Great for oxtail, lamb shank, beef stew, curry, potjie-style dishes with no attention."},
{"id":"deep-fryer","name":"Deep fryer (or deep pan of oil)","heat":"Hot oil convection — food immersed in 160–190°C oil","simple":"Oil absorbs and holds heat; immersing food transfers heat fast from all surfaces. Water inside turns to steam, pushing outward while oil seals the surface into a crisp crust.","expect":"Fast, golden crisp exterior, moist interior, characteristic fried flavour; oil reusable if strained.","adjust":"170–190°C typically; don't overcrowd (drops oil temp); drain on paper; cool oil fully before storing.","best_for":"Chips, vetkoek, fish, chicken, samoosas, spring rolls, batters.","watch":"Oil temp critical — too cool = greasy, too hot = burnt outside/raw inside; water splatters dangerously.","sa":"Essential for slap chips, vetkoek, fish and chips, fried chicken, Cape Malay samoosas."},
{"id":"sous-vide","name":"Sous vide","heat":"Precise temperature-controlled water bath","simple":"Food sealed in a bag sits in water held at the exact target temperature; heat slowly penetrates until the food matches the water. It cannot overcook — temperature never exceeds the setpoint.","expect":"Edge-to-edge exact doneness; tender, no moisture loss; needs a sear afterwards for colour/crust.","adjust":"Set bath to target final temp (54–65°C for meat); 1–48 hr by thickness; sear in a hot pan or with a torch after.","best_for":"Steak, lamb chops, pork loin, fish fillets, eggs.","watch":"No browning without a post-sear; long times; food-safety with extended low-temp cooks.","sa":"Great for premium cuts — braai-quality steak to exact medium-rare, lamb chops, fillet."},
{"id":"smoker","name":"Smoker","heat":"Low indirect heat + wood smoke","simple":"A fire burns low (100–130°C) making smoke that circulates around the meat; smoke compounds flavour the surface while low heat slowly breaks down collagen.","expect":"Distinct smoky flavour, a reddish smoke ring, pull-apart tenderness, dark bark; long cooks (6–18 hr).","adjust":"100–130°C; wood choice (oak, hickory, fruitwoods) changes flavour; hold steady temp; push through the ~70°C stall.","best_for":"Brisket, pork ribs, shoulder, lamb shoulder, boerewors.","watch":"Long planning; temp control critical; too much smoke turns bitter; safe temp takes hours.","sa":"Fits SA braai culture — smoked brisket, ribs, lamb shoulder, boerewors with real wood smoke."},
{"id":"pizza-oven","name":"Pizza oven / high-temperature wood oven","heat":"High-temp radiation + convection from stone floor and dome","simple":"The oven reaches 350–450°C — far hotter than domestic ovens. The stone floor conducts into the base, cooking it in seconds; dome heat and flame give rapid browning and char.","expect":"Restaurant pizza in 60–90 sec; crispy puffed leopard-spotted crust; rapid cook keeps toppings fresh.","adjust":"Preheat stone to 350–400°C+; launch with a peel; rotate halfway; wood adds smoky char.","best_for":"Pizza, flatbreads, bread, high-temp veg and meats.","watch":"Extreme temps — inattention burns it in seconds; learning curve for launching.","sa":"Great for wood-fired pizza with braai-inspired or Cape Malay flatbread toppings."}
];
window.FATS={
"masterclass":{
  "id":"fats-and-oils","term":"Fats & Oils — Choosing Your Cooking Fat","family":"Heat transfer · fat as the cooking medium",
  "native":"Old English 'fett' — the foundational cooking medium across all cuisines, carrying both heat and flavour.",
  "why":"A smoke point is the temperature where a fat's molecules break down and burn, producing acrid smoke and harmful compounds. Unrefined fats (extra-virgin olive oil, butter) hold proteins, sugars and flavour compounds that burn at lower temperatures — flavourful but heat-sensitive. Refined oils strip those impurities, raising the smoke point for high-heat cooking. The real harm is burning ANY fat past its smoke point, not the fat itself. Saturated fats (coconut, animal fats) are stable at high heat; monounsaturated (olive, avocado) are moderately stable and heart-friendly; polyunsaturated (vegetable, sunflower) are fragile and oxidise easily.",
  "heritage":"Mediterranean kitchens built on olive oil; Indian cooking on ghee's high heat and nutty aroma; French cuisine on duck fat and butter; steakhouses on beef tallow; SA braai masters on animal fats or stable plant oils over high coals.",
  "wisdom":"Match smoke point to method: high-heat sear (230°C+) wants refined oils or ghee; medium sauté (~180°C) works with olive oil; flavourful fats finish. Never burn your fat — it ruins flavour and nutrition.",
  "mastery":["Match the fat's smoke point to the cook: high-heat sear (230°C+) wants avocado oil, refined oil or ghee — not butter or EVOO.","Use flavourful fats (EVOO, butter, sesame, duck fat) to FINISH or for low-medium heat only.","Clarify butter into ghee when you want butter flavour at high heat — it removes the milk solids that burn.","Never let oil smoke past its point — it turns acrid and harmful, creating free radicals.","Store oils away from heat and light; use within 6–12 months.","Save expensive flavourful oils for finishing — cheap neutral oils do the heavy lifting.","A little goes a long way: most pans need only 1–2 teaspoons."],
  "mistakes":["Deep-frying in extra-virgin olive oil — burns at ~190°C, wastes money, tastes bitter.","Heating non-stick pans dry — add oil before heating to protect the coating.","Reusing burnt oil — once it has smoked and darkened it's rancid and harmful.","Storing oil next to the stove or in sunlight — heat and light speed oxidation.","Using butter for high-heat searing — milk solids burn at ~150°C, turning black and bitter."],
  "metric":"Read the oil: shimmering waves appear near 180°C; the first wisp of smoke means you're at or past the smoke point — drop the heat at once.",
  "dishes":[]
},
"table":[
  {"fat":"Extra-virgin olive oil","smoke_point_c":190,"type":"Unrefined · flavourful","best_for":"Finishing, low-medium sauté, dressings, drizzling","flavour":"Fruity, peppery, grassy","health":"High in heart-healthy monounsaturated fat + antioxidants; best raw or gentle heat","sa_note":"SA produces excellent EVOO (Western Cape); finishing oil of choice"},
  {"fat":"Butter (unsalted)","smoke_point_c":150,"type":"Unrefined · flavourful","best_for":"Finishing, low-heat baking, sauces, spreading","flavour":"Rich, creamy, slightly sweet","health":"Saturated fat with fat-soluble vitamins (A, D, E, K); use sparingly","sa_note":"SA butter is excellent for baking and finishing; not for high heat"},
  {"fat":"Ghee (clarified butter)","smoke_point_c":250,"type":"Refined · flavourful","best_for":"High-heat searing, curries, roasting, frying","flavour":"Nutty, toasty, rich butter aroma","health":"Lactose-free, concentrated healthy fats; very stable at high heat","sa_note":"Essential in Indian cooking; increasingly popular in SA kitchens"},
  {"fat":"Light/regular olive oil","smoke_point_c":240,"type":"Refined · neutral","best_for":"Medium-high sauté, roasting, general cooking","flavour":"Mild, neutral olive notes","health":"Heart-healthy monounsaturated; fewer antioxidants than EVOO","sa_note":"Good everyday workhorse oil; more stable than EVOO for cooking"},
  {"fat":"Canola/rapeseed oil","smoke_point_c":200,"type":"Refined · neutral","best_for":"Frying, baking, general cooking","flavour":"Neutral, mild","health":"Low saturated, high monounsaturated; good omega-3:omega-6 ratio","sa_note":"Widely available and affordable in SA; good all-purpose oil"},
  {"fat":"Vegetable oil","smoke_point_c":230,"type":"Refined · neutral","best_for":"Frying, high-heat cooking, baking","flavour":"Neutral","health":"Mostly polyunsaturated; use in moderation, avoid overheating","sa_note":"Common in SA households; cheapest frying option"},
  {"fat":"Sunflower oil","smoke_point_c":230,"type":"Refined · neutral","best_for":"Frying, roasting, general cooking","flavour":"Neutral, mild","health":"High polyunsaturated + vitamin E; not for high-heat reuse","sa_note":"Very common in SA; affordable frying oil"},
  {"fat":"Avocado oil (refined)","smoke_point_c":270,"type":"Refined · neutral to mildly nutty","best_for":"High-heat searing, frying, grilling, roasting","flavour":"Mild, buttery, slightly nutty","health":"High monounsaturated + vitamin E; excellent heat stability","sa_note":"Premium oil; increasingly in SA health stores"},
  {"fat":"Coconut oil (refined)","smoke_point_c":230,"type":"Refined · neutral","best_for":"High-heat cooking, baking, frying","flavour":"Neutral","health":"High saturated; very heat-stable, contested health profile","sa_note":"Popular in baking and curries; refined is neutral"},
  {"fat":"Coconut oil (virgin)","smoke_point_c":180,"type":"Unrefined · flavourful","best_for":"Low-medium heat, baking, curries, desserts","flavour":"Distinct coconut aroma","health":"High saturated with MCTs; heat-stable but distinctive","sa_note":"Adds tropical flavour; use deliberately, not all-purpose"},
  {"fat":"Toasted sesame oil","smoke_point_c":180,"type":"Unrefined · flavourful","best_for":"Finishing, dressings, marinades, stir-fry finishing","flavour":"Intense nutty, toasted aroma","health":"High polyunsaturated + antioxidants; use sparingly for flavour","sa_note":"Essential for Asian-inspired dishes; a little goes a long way"},
  {"fat":"Beef tallow","smoke_point_c":250,"type":"Unrefined · flavourful","best_for":"High-heat searing, frying, roasting potatoes, braai","flavour":"Rich, beefy, savoury","health":"Saturated animal fat; very heat-stable, traditional","sa_note":"Traditional steakhouse fat; superb for burgers and roast potatoes"},
  {"fat":"Duck fat","smoke_point_c":190,"type":"Unrefined · flavourful","best_for":"Roasting potatoes, confit, sautéing, finishing","flavour":"Rich, silky, slightly gamey","health":"Mostly mono- and saturated; prized for flavour","sa_note":"French classic; incredible for potatoes and confit"},
  {"fat":"Lard (pork fat)","smoke_point_c":190,"type":"Unrefined · mild","best_for":"Baking (pastry), frying, roasting","flavour":"Mild, porky, subtle","health":"Less saturated than butter; high monounsaturated; traditional","sa_note":"Traditional baking fat; makes excellent flaky pastry"},
  {"fat":"Schmaltz (chicken fat)","smoke_point_c":190,"type":"Unrefined · flavourful","best_for":"Matzo balls, Jewish cooking, roasting veg, finishing","flavour":"Rich, savoury, chicken essence","health":"Similar to lard; traditional with cultural significance","sa_note":"Traditional in Jewish cooking; increasingly popular for flavour"},
  {"fat":"Peanut oil","smoke_point_c":230,"type":"Refined · mildly nutty","best_for":"Frying, stir-frying, high-heat cooking","flavour":"Mild nutty aroma","health":"High monounsaturated; good heat stability","sa_note":"Excellent for frying; classic in Asian and African cooking"}
]};
window.HERBS={
"masterclass":{
  "id":"herbs-spices-pairing","term":"Herbs, Spices & the Pairing Compass","family":"Flavour · pairing science",
  "native":"From Latin herba (grass) — the ancient art of reading flavour patterns in ingredients.",
  "why":"Classic pairings work because ingredients share aroma compounds — the flavour-pairing principle. Lamb and rosemary both carry pinene; tomato and basil share linalool. Fresh herbs are bright and delicate (add late); dried spices are concentrated and need fat to bloom (add early). The art is balancing a heavy protein with a cutting herb: lamb meets piney rosemary, fatty pork meets earthy sage, delicate fish meets clean dill.",
  "heritage":"Every cuisine built signature pairings: Italy made basil belong to tomato, India forged the cumin-coriander base, France matched tarragon to chicken, and SA's Cape Malay kitchens wove cinnamon, clove and turmeric into bobotie — all discovered through taste, not chemistry.",
  "wisdom":"Start with one hero herb or spice and build. Dried spices go in early to bloom in fat; fresh herbs finish. Taste as you go — acid and salt carry the flavour.",
  "mastery":["Add dried spices early to hot fat so they bloom and release their oils.","Fresh herbs go in at the end — heat kills their bright oils.","Match woody herbs (rosemary, thyme, sage) to robust red meats.","Pair soft herbs (basil, dill, coriander, mint) with delicate proteins.","One hero spice per dish — layer gradually.","Toast whole spices before grinding to wake their oils.","Don't overcrowd flavours — let one note sing."],
  "mistakes":["Burning delicate herbs by adding them too early — they turn bitter.","Throwing all spices in at once — layer them for depth.","Using stale dried herbs — they should smell potent, not dusty.","Over-spicing — salt and acid do the heavy lifting.","Forgetting dried herbs are stronger than fresh — use half the amount."],
  "metric":"Taste and ask: would this sing with a squeeze of lemon or a pinch of salt?",
  "dishes":[]
},
"families":[
  {"family":"Warm sweet spices","members":["cinnamon","cloves","nutmeg","allspice","cardamom"],"pairs_with":["lamb","pumpkin","butternut","fruit bakes","bobotie","breads","milk puddings"],"vibe":"Sweet-warm and festive — Cape Malay and baking backbone"},
  {"family":"Earthy seed spices","members":["cumin","coriander seed","fennel","mustard seed","fenugreek"],"pairs_with":["beef","lamb","lentils","mince","curries","sausages","root veg"],"vibe":"Grounded and savoury — the backbone of stews and spice blends"},
  {"family":"Chillies & heat","members":["fresh chilli","cayenne","paprika","peri-peri"],"pairs_with":["chicken","pork","prawns","eggs","tomatoes","corn","braai marinades"],"vibe":"Bright heat that cuts richness — African and Latin soul"},
  {"family":"Woody herbs","members":["rosemary","thyme","oregano","sage","bay"],"pairs_with":["lamb","beef","chicken","pork","potatoes","bread","stews","braais"],"vibe":"Hardy and resinous — built for long cooking and red meats"},
  {"family":"Soft fresh herbs","members":["basil","coriander leaf","dill","parsley","mint","tarragon"],"pairs_with":["tomato","fish","chicken","cucumber","yoghurt","salads","curries"],"vibe":"Bright and delicate — finish dishes, don't cook them"},
  {"family":"Warm aromatics","members":["ginger","garlic","onion","lemongrass"],"pairs_with":["chicken","prawns","fish","stir-fries","curries","soups","marinades"],"vibe":"The flavour foundation — start here, build everything on top"},
  {"family":"Warming roots","members":["turmeric","galangal"],"pairs_with":["rice","chicken","fish","lentils","curries","soups"],"vibe":"Earthy and golden — anti-inflammatory powerhouses"},
  {"family":"Seeds as texture","members":["nigella","sesame","poppy"],"pairs_with":["breads","naan","biscuits","salads","vegetables","oils"],"vibe":"Crunch and nuttiness — the finish that makes food memorable"}
],
"pairings":[
  {"herb":"Rosemary","loves":"lamb","mnemonic":"Rosemary loves lamb","why":"Piney resin cuts lamb's richness","also":["beef","potatoes","focaccia","white beans"]},
  {"herb":"Basil","loves":"tomato","mnemonic":"Basil belongs to tomato","why":"Both share sweet, peppery linalool notes","also":["mozzarella","pasta","prawns","peaches"]},
  {"herb":"Sage","loves":"pork","mnemonic":"Sage is made for pork","why":"Earthy camphor cuts fatty sweetness","also":["chicken","pumpkin","risotto","butter"]},
  {"herb":"Thyme","loves":"chicken","mnemonic":"Thyme is fine for chicken","why":"Gentle earthiness that won't overpower","also":["stock","mushrooms","root veg","wine sauces"]},
  {"herb":"Mint","loves":"lamb","mnemonic":"Mint and lamb were always meant","why":"Cool brightness balances richness","also":["peas","yoghurt","cucumber","chocolate"]},
  {"herb":"Dill","loves":"fish","mnemonic":"Dill and fish, a perfect dish","why":"Light aniseed complements delicate proteins","also":["cucumber","potatoes","yoghurt","eggs"]},
  {"herb":"Oregano","loves":"tomato","mnemonic":"Oregano owns tomato","why":"Punchy and floral — Greek and Italian soul","also":["lamb","chicken","aubergine","feta"]},
  {"herb":"Tarragon","loves":"chicken","mnemonic":"Tarragon takes to chicken","why":"Aniseed warmth shines with white meat","also":["eggs","fish","mustard","cream sauce"]},
  {"herb":"Coriander leaf","loves":"curry","mnemonic":"Coriander brightens everything","why":"Citrus lift cuts spice heat","also":["Asian dishes","Mexican","prawns","yoghurt"]},
  {"herb":"Cumin","loves":"beef","mnemonic":"Cumin calls for beef","why":"Earthy warmth grounds red meat","also":["lentils","mince","chickpeas","aubergine"]},
  {"herb":"Paprika","loves":"chicken","mnemonic":"Paprika paints chicken","why":"Smoky sweetness adds depth and colour","also":["pork","potatoes","eggs","stews"]},
  {"herb":"Turmeric","loves":"rice","mnemonic":"Turmeric tints rice","why":"Earthy golden warmth permeates grains","also":["curries","chicken","lentils","cauliflower"]},
  {"herb":"Cinnamon","loves":"lamb","mnemonic":"Cinnamon crowns lamb","why":"Sweet warmth complements gamey richness","also":["bobotie","pumpkin","breads","milk puddings"]},
  {"herb":"Cloves","loves":"ham","mnemonic":"Cloves clothe ham","why":"Intense spice pierces saltiness","also":["bakes","beef","pickles","fruit"]},
  {"herb":"Cardamom","loves":"coffee","mnemonic":"Cardamom crowns coffee","why":"Floral sweetness lifts roast bitterness","also":["bakes","milk puddings","curries","breads"]},
  {"herb":"Bay leaf","loves":"stock","mnemonic":"Bay leaf backs stock","why":"Subtle herbal depth for long cooks","also":["braises","stews","rice","soup"]},
  {"herb":"Peri-peri","loves":"chicken","mnemonic":"Peri-peri powers chicken","why":"African heat that built a tradition","also":["prawns","fish","corn","braai"]}
],
"mnemonics":["Rosemary loves lamb","Basil belongs to tomato","Sage is made for pork","Thyme is fine for chicken and wine","Mint and lamb were always meant","Dill and fish, a perfect dish","Cumin calls for beef and lentils","Coriander brightens everything grander","Tarragon takes to chicken","Oregano owns tomato","Cinnamon crowns lamb","Cardamom crowns coffee","Bay leaf backs stock","Peri-peri powers chicken"]
};
/* Surface the Fats & Herbs/Spices MASTERCLASSES through the existing Method Map
   plumbing (same concat pattern as masterclass-extra.js), so they're visible now.
   The richer tables (fat smoke-points, pairing families/mnemonics, appliance atlas)
   stay here for the dedicated "How Heat Works" module build. */
if(window.MASTERCLASS&&window.FATS&&FATS.masterclass&&!MASTERCLASS.find(function(m){return m.id===FATS.masterclass.id;}))MASTERCLASS.push(FATS.masterclass);
if(window.MASTERCLASS&&window.HERBS&&HERBS.masterclass&&!MASTERCLASS.find(function(m){return m.id===HERBS.masterclass.id;}))MASTERCLASS.push(HERBS.masterclass);
if(window.MC_DOMAIN){Object.assign(window.MC_DOMAIN,{'fats-and-oils':'fat','herbs-spices-pairing':'foundations'});}
