/* MASTERCLASS EXPANSION — 12 new technique masterclasses (breadth pass).
   Concatenates onto window.MASTERCLASS and registers each new id -> domain
   in MC_DOMAIN so they pull through the Method Map. SA-localized: °C / g / ml /
   tsp / tbsp / braai / coriander. No emoji, no cups/oz/°F. */
window.MASTERCLASS=(window.MASTERCLASS||[]).concat([
  {
    "id":"deglazing",
    "term":"Deglazing & Pan Jus",
    "family":"Wet heat · fond extraction",
    "native":"French — déglacer, 'to loosen the glaze'; dissolving the caramelised deposit left by seared meat",
    "why":"The science: the fond is a concentrate of Maillard reaction products — proteins and sugars caramelised onto the pan. Adding liquid dissolves these through solubilisation and gentle hydrolysis, while the alcohol in wine acts as a solvent for fat-soluble flavours water alone can't reach. As the liquid reduces, flavour compounds concentrate and naturally emulsify with rendered fat into a glossy, self-thickened sauce.",
    "heritage":"Central to French cuisine (sauce chasseur) and adapted globally — Italian sugo d'arrosto, British jus, and the pan juices saved after a South African Sunday roast. Every culture that roasts meat found the pan holds the essence of the dish.",
    "wisdom":"The pan makes more flavour than the meat — treat the fond as gold, not waste. Deglaze the moment the protein leaves the pan; once the fond dries to a black crust it is burnt and bitter. Scrape with wood, never metal.",
    "mastery":["Remove the protein; pour off excess fat, leaving 1–2 tbsp behind.","Set the pan over medium heat; sweat aromatics (shallot, garlic) briefly.","Pour in cold liquid (wine, stock, or both) — it should hiss violently.","Scrape every brown bit with a wooden spoon, dissolving the fond completely.","Simmer until reduced by half to three-quarters; finish with cold butter for gloss."],
    "mistakes":["Adding liquid to a screaming-hot pan — dangerous splatter.","Using non-stick — there is no fond to deglaze.","Over-reducing until salty or bitter — taste every 2 minutes.","Not pouring off fat first — the sauce ends up greasy and split."],
    "doneness":"Coats the back of a spoon (nappe) and leaves a clear trail when a finger is drawn through it; glossy, not opaque.",
    "requires":{"kit":["stainless or cast-iron pan (never non-stick)","wooden spoon","fine-mesh strainer (optional)","ladle"]},
    "dishes":["steak-frites-cafe-de-paris","coq-au-vin","lamb-shank-red-wine","red-wine-braised-short-rib"]
  },
  {
    "id":"tempering-eggs",
    "term":"Tempering Eggs",
    "family":"Egg cookery · protein coagulation control",
    "native":"French — tempérer; gradually equalising temperature to prevent shock",
    "why":"The science: egg proteins coagulate abruptly above roughly 70°C. If hot liquid hits cold eggs directly, local proteins cook into scrambled curds before they can disperse. Tempering introduces heat in small increments, letting proteins unfold and thicken the mixture uniformly without coagulating. Starch (flour or cornflour) further stabilises by slowing protein movement.",
    "heritage":"The technique behind French crème anglaise and ice-cream bases, Chinese egg-drop soup, Italian carbonara (pasta water warms the yolks) and South African melktert. Every custard cuisine — from Portuguese pastel de nata to Japanese chawanmushi — relies on it.",
    "wisdom":"Whisk constantly and never stop — motion distributes heat instantly. Add hot liquid in a thin stream, not all at once. If it starts to grain, it is too late: strain it and accept a thinner result.",
    "mastery":["Whisk eggs (and sugar, if using) until pale and thick.","Heat the liquid (cream, milk, or pasta water) just below a simmer; remove from heat.","Ladle a small amount (about 10%) of hot liquid into the eggs, whisking vigorously.","Repeat with two more slightly larger additions until the eggs are warm to the touch.","Pour the tempered mix back into the main liquid and cook gently until thickened (nappe)."],
    "mistakes":["Adding hot liquid in one go — instant scrambled eggs.","Stopping the whisk — eggs cook on the bottom of the bowl.","Overheating after tempering — it curdles despite the care.","No temperature difference — then tempering isn't needed at all."],
    "doneness":"Coats the back of a spoon (nappe); 80–82°C on a thermometer for custards.",
    "requires":{"kit":["whisk","heatproof bowl","ladle","instant-read thermometer","fine-mesh strainer (insurance)"]},
    "dishes":["creme-brulee","carbonara","melktert"]
  },
  {
    "id":"mise-en-place",
    "term":"Mise en Place",
    "family":"Kitchen workflow · preparation discipline",
    "native":"French — 'put in place'; the professional cook's practice of preparing all ingredients before heat goes on",
    "why":"The science: cooking is time-sensitive and temperature-critical. Once heat is applied, reactions proceed in seconds, not minutes. Hunting for spices or chopping while something sautés throws off timing — the garlic burns, the sear fails, the sauce over-reduces. Mise en place moves all prep into a low-stakes window, preserving focus for the cook itself.",
    "heritage":"Codified in French brigade kitchens, adopted globally by chefs, popularised for home cooks by Julia Child and Jacques Pépin. In South Africa the braai master readies fire, marinades and sides long before guests arrive — same discipline, different name.",
    "wisdom":"Read the recipe to the end first — no surprises. Prep into small bowls in order of use. Clean as you go. If you're searching while cooking, you've already failed.",
    "mastery":["Read the recipe completely; visualise the steps and timing.","Gather and measure everything — chop, mince, grate, portion.","Arrange in order of use: first to use, closest to the stove.","Preheat pans and ovens before you start — no waiting.","Taste and season each component before it hits the heat."],
    "mistakes":["Cooking before reading the full recipe — forgotten ingredients, wrong timing.","Chopping while something sautés — burnt aromatics and panic.","Not measuring — 'a splash' becomes a flood under stress.","A cluttered bench — crossed wires, dropped tools."],
    "metric":"When the heat goes on, your hands are empty and all you do is cook — no searching, no chopping, no measuring.",
    "requires":{"kit":["cutting board","chef's knife","measuring spoons","small bowls or ramekins","kitchen scale"]},
    "dishes":[]
  },
  {
    "id":"acid-brightness",
    "term":"Acid & Brightness (Finishing)",
    "family":"Flavour balance · seasoning",
    "native":"Global — every cuisine has a 'sour' element; French acidité, Chinese suan, South African 'a squeeze of lemon'",
    "why":"The science: acid (H+ ions) activates sour receptors and suppresses bitter perception, creating the impression of 'brightness' — food tastes alive rather than flat. It also volatilises aromatic compounds, intensifying smell. Salt amplifies flavour; fat carries it; acid makes it pop. The final addition matters because heat destroys volatile acids and long cooking mellows sharpness — the bright jolt must be fresh.",
    "heritage":"Lemon in Mediterranean cooking, vinegar in Chinese stir-fries, tamarind in Indian curries, lime in Mexican salsas. In South Africa, a squeeze of lemon over braaied fish or a dash of vinegar in pap — the universal final adjustment.",
    "wisdom":"Taste before and after — the difference is undeniable. Add acid at the end, not the start. A little goes a long way; start small. When in doubt, lemon and vinegar are interchangeable.",
    "mastery":["Cook the dish completely; taste and adjust salt first.","Add acid a few drops at a time — lemon juice, vinegar, or wine.","Taste after each addition; stop when flavours 'wake up'.","If you over-acidify, add a pinch of sugar or fat to rebalance.","Serve immediately — brightness fades."],
    "mistakes":["Adding acid at the start — it cooks off and the dish tastes flat.","Overdoing it — sour rather than bright.","Forgetting salt first — acid alone can't fix under-seasoned food.","Using only one acid — different vinegars and citrus add layers."],
    "metric":"The food tastes 'alive' — flavours distinct, not muddy; a subtle sharpness at the sides of the tongue.",
    "requires":{"kit":["microplane (for zest)","citrus juicer","vinegars","tasting spoon"]},
    "dishes":[]
  },
  {
    "id":"risotto-staged-stock",
    "term":"Risotto & the Staged-Stock Method",
    "family":"Moist heat · starch extraction",
    "native":"Italian — from riso, 'rice'; the technique that turns rice creamy without a drop of cream",
    "why":"The science: arborio or carnaroli rice is high in amylopectin, a branched starch that leaches out when heated and agitated. Each ladle of hot stock forces the rice to absorb liquid then release starch, building a velvety emulsion. The creaminess is starch + stock + butter + parmesan — never cream itself.",
    "heritage":"The hallmark of Lombardy and Piedmont, perfected in Milan (risotto alla milanese with saffron). It spread globally as the restaurant showpiece that proves a cook's patience and rhythm.",
    "wisdom":"Every nonna and chef agrees: hot stock, dry rice toasted first, constant stirring, one ladle at a time. The rice tells you when it needs more — when the liquid disappears and the surface goes glossy.",
    "mastery":["Toast rice in hot fat until the grains smell nutty and edges turn translucent.","Deglaze with wine (optional); let it evaporate completely.","Add simmering stock one ladle at a time — never cold, never all at once.","Stir constantly to abrade the grains and release starch.","Finish off the heat with cold butter and parmesan — the mantecatura."],
    "mistakes":["Adding cold stock — temperature shock halts starch release.","Adding stock too fast — it boils like porridge, not creamy.","Undercooking — chalky grains defeat the point.","Overcooking — it blows out to mush, no texture."],
    "doneness":"Grains tender with a white pinprick centre (al dente) and the mixture waves like lava when you shake the pan — about 18–20 min.",
    "requires":{"kit":["heavy wide pan","ladle","wooden spoon","stock pot for hot stock","cheese grater"]},
    "dishes":["risotto-milanese"]
  },
  {
    "id":"pasta-al-dente",
    "term":"Pasta — Al Dente & Starch Water",
    "family":"Boiling · emulsification",
    "native":"Italian — 'to the tooth'; pasta cooked tender but with firm resistance at the centre",
    "why":"The science: pasta water turns cloudy as surface starch leaches out. When you finish pasta in its sauce with a splash of this water, starch and fat emulsify into a silky coating that clings. Proper seasoning needs heavily salted water — roughly 10 g salt per litre, 'salty as the sea'.",
    "heritage":"Non-negotiable in Italy and pasta bars worldwide. The sign of a serious cook: always tasting a strand two minutes before the packet says, and always saving the water.",
    "wisdom":"The universal rules: massive pot, heavily salted water, vigorous boil, stir immediately, cook one minute under packet time, reserve the water. Pasta finishes in the sauce, not the water.",
    "mastery":["Salt the water aggressively — it should taste like the sea.","Add pasta to boiling water; stir immediately to prevent sticking.","Check two minutes before packet time — still a white core.","Reserve a mug of cloudy pasta water before draining.","Add pasta to the sauce with a splash of starch water; toss over high heat to emulsify."],
    "mistakes":["Under-salting the water — pasta itself tastes bland.","Overcooking to mush — no texture, no sauce adhesion.","Rinsing after draining — washes away the starch you need.","Tossing with oil — sauce slides right off."],
    "doneness":"Al dente — tender but with firm resistance when bitten; the white pinprick of uncooked centre gone but the grain visible.",
    "requires":{"kit":["large stock pot (6 litre+)","colander or spider","tongs","mug for starch water"]},
    "dishes":["carbonara","lasagne-bolognese","linguine-vongole-clams","spaghetti-bolognese"]
  },
  {
    "id":"glazing-vegetables",
    "term":"Glazing Vegetables (Glacé)",
    "family":"Moist heat · butter-glazed",
    "native":"French — à la glacé; glazed in a glossy syrup until tender and coated",
    "why":"The science: a little water, butter and sugar cooks the vegetable covered. As it softens, the water evaporates and the butter emulsifies with remaining sugars into a glossy ivory glaze that clings. It is steaming then glazing in one pan.",
    "heritage":"The foundation of the French bourgeois kitchen and the classic garnish brigade — glazed carrots, turnips, pearl onions. Essential from refined kitchens to the family braai.",
    "wisdom":"Every chef learns the same sequence: even cuts, start covered with butter, water, salt and sugar, cook until the water vanishes and butter emulsifies into glaze. Shake the pan, don't stir.",
    "mastery":["Cut vegetables into even sizes for uniform cooking.","Place in a wide pan with butter, a pinch each of salt and sugar, and just enough water to half-cover.","Cover and cook over medium heat until the water almost evaporates and vegetables are tender.","Uncover and shake the pan as the remaining water turns to glossy syrup.","Finish with fresh herbs and a squeeze of lemon."],
    "mistakes":["Too much water — it boils instead of glazing.","Too much heat before the water reduces — butter separates or burns.","Uneven cutting — some mush while others stay raw.","Skipping the sugar or salt — the glaze needs both balance and sheen."],
    "doneness":"Tender but holding shape, coated in a glossy ivory glaze; the pan looks dry, not swimming.",
    "requires":{"kit":["wide sauté pan with lid","sharp knife","measuring spoons","tongs"]},
    "dishes":[]
  },
  {
    "id":"caramelised-onions",
    "term":"Caramelised Onions",
    "family":"Dry heat · slow browning",
    "native":"French — caramélisation; the slow oxidation of sugar into deep brown flavour compounds",
    "why":"The science: onions are about 10% sugar by weight. Near 160°C these sugars break down via caramelisation into hundreds of new molecules — nutty, savoury, sweet. The long slow cook drives off moisture and concentrates flavour. Deglazing with water when fond builds dissolves the browned sugars back into the onions.",
    "heritage":"Across French bistros, American diners and Middle-Eastern kitchens — wherever onions meet low heat and patience. The base of French onion soup, a classic pizza topping, the Persian condiment that turns rice into celebration food.",
    "wisdom":"All traditions converge: low heat, fat, patience, and water when it sticks. Rush and you burn. Stir often and deglaze when the pan goes brown — pale gold is nothing, mahogany is gold.",
    "mastery":["Slice evenly; use a wide pan with more fat than you think.","Start medium-high to get them sweating and beginning to colour.","Drop to low and cook 30–45 min, stirring every 5–10 min.","When fond builds and the pan threatens to catch, deglaze with a splash of water.","Season with salt late — salt draws moisture and slows browning."],
    "mistakes":["High heat all the way — char before caramel.","Crowding the pan — they boil in their own juice.","Adding sugar — onions have plenty; sugar burns.","Salting too early — draws water, they steam instead of brown."],
    "metric":"Deep mahogany colour, sweet-savoury aroma, reduced to about a quarter of their volume; a dark sticky fond that dissolves back in when deglazed.",
    "requires":{"kit":["wide heavy pan","sharp knife","wooden spoon","ladle for water"]},
    "dishes":["french-onion-soup"]
  },
  {
    "id":"breading-crumbing",
    "term":"Breading & Crumbing",
    "family":"Dry heat · three-stage coating",
    "native":"German — schnitzel, 'little cut'; the Viennese take on Italian cotoletta alla milanese",
    "why":"The science: flour gives a dry base that adheres to the protein, egg wash is the glue (egg proteins coagulate when heated, bonding flour and crumbs), and breadcrumbs form the crisp matrix through water evaporation and starch gelatinisation. A 10–15 min rest lets the coating set — without it, steam escapes during frying and the crust peels away.",
    "heritage":"The European schnitzel tradition met British fish and chips and Japanese katsu — every culture found that flour-egg-crumb equals crunch. South African chicken schnitzel, crumbed calamari and crumbed lamb chops are local staples.",
    "wisdom":"Every grandmother's kitchen converges: three shallow bowls (flour, egg, crumbs), dry meat, press the crumbs in, let it rest. The crust tells you when it's ready — golden, firm, fully adhered.",
    "mastery":["Pat the surface bone-dry — moisture breaks the flour seal.","Season the flour well (salt, pepper, paprika) — this is your flavour base.","Dust in flour, shake off excess, dip in egg wash, then press into crumbs.","Press firmly — crumbs must embed, not just sit on the surface.","Rest on a rack 10–15 min to set the coating before frying."],
    "mistakes":["Wet meat — the flour never grips and the coating slides off.","Skipping the rest — steam blows the crust apart in hot oil.","Not pressing the crumbs — a loose layer that sheds immediately.","Crowding the pan — oil temperature drops, coating goes soggy."],
    "doneness":"Golden-brown and firm; internal 74°C for chicken or pork.",
    "requires":{"kit":["three shallow bowls","tongs","wire rack for resting","heavy pan","instant-read thermometer"]},
    "dishes":["chicken-schnitzel"]
  },
  {
    "id":"working-sugar-caramel",
    "term":"Working Sugar (Caramel)",
    "family":"Dry heat · sugar transformation",
    "native":"French — caramel; the art of controlling sugar's thermal breakdown from syrup to bitter complexity",
    "why":"The science: sugar has no real liquid state — it melts and caramelises around 160–180°C, decomposing into hundreds of compounds (furans, pyrazines, diacetyl). Wet caramel (sugar + water) gives more control; dry caramel cooks faster but risks burning. Stages progress: thread (106–110°C), soft ball (118°C), hard crack (149°C), deep amber (180°C). Beyond ~185°C it turns bitter and acrid.",
    "heritage":"French pâtisserie (crème caramel, tarte tatin), British sticky toffee, South African peppermint crisp tart — every cuisine found that controlled sugar burn equals depth. Cape Malay koeksisters rely on caramelised syrup.",
    "wisdom":"Generations of confectioners agree: respect the heat curve, watch the colour, never walk away. Sugar holds heat and keeps cooking off the flame — timing is everything.",
    "mastery":["Wet method: dissolve sugar in water over low heat; swirl, don't stir.","Brush down crystals from the sides with a wet pastry brush.","Cook to deep amber — it keeps darkening off the heat.","Remove at once; plunge the pan base in cold water to stop the cook.","Deglaze carefully with warm cream (stand back — it volcano-spits)."],
    "mistakes":["Stirring crystallised sugar — encourages a grainy mess.","Walking away — amber to burnt in 15 seconds.","Adding cold liquid to hot caramel — it seizes hard instantly.","A thin pan — hotspots mean uneven colour and bitter spots."],
    "metric":"Colour is your cue: pale gold (~170°C) for subtle sweetness, deep amber (~180°C) for bitter complexity.",
    "requires":{"kit":["heavy-based stainless or copper pan","pastry brush","thermometer","heat-proof spatula"]},
    "dishes":["sticky-toffee-pudding","peppermint-crisp-tart","creme-brulee"]
  },
  {
    "id":"toasting-blooming-spices",
    "term":"Toasting & Blooming Spices",
    "family":"Dry and wet heat · volatile oil extraction",
    "native":"Indian — tarka (tempering) and bhunao (toasting); heat wakes dormant aromatic compounds in seeds and pods",
    "why":"The science: whole spices hold volatile oils trapped in cell structures. Dry-toasting (150–180°C) ruptures cells and vaporises monoterpenes — why toasted cumin smells like cumin. Blooming ground spices in hot oil lets fat-soluble compounds dissolve into the oil, carrying flavour deeper into the dish. Dry-toasting is for aroma; blooming is for integration.",
    "heritage":"Indian tarka (tempering spices in ghee), Middle Eastern blends toasted before use, Cape Malay bredie where spices are bloomed in oil before the meat — every spice culture found that heat equals expression.",
    "wisdom":"Spice merchants across continents agree: toast whole, never ground; bloom ground, never whole. The nose knows — when the room fills with aroma, the spice is ready.",
    "mastery":["Dry-toast whole spices in a dry pan over medium heat, shaking constantly.","Listen for the 'pop' of mustard seeds and watch for colour to deepen (1–2 min).","Remove at once — they keep toasting in the hot pan.","Cool completely, then grind to retain volatile oils.","Bloom ground spices: add to hot oil, fry 10–15 sec until the sizzle subsides."],
    "mistakes":["Toasting ground spices — they burn instantly and turn bitter.","Walking away — seeds go from toasted to charcoal in seconds.","Grinding hot — heat disperses oils and the blend goes stale.","Blooming in cool oil — flavours stay trapped and never release."],
    "metric":"Whole spices: fragrant, slightly darker, 1–2 minutes. Ground spices blooming: sizzling then fragrant, 10–15 seconds.",
    "requires":{"kit":["small heavy pan","mortar and pestle or spice grinder","spatula","airtight jar"]},
    "dishes":["durban-mutton-curry","butter-chicken","cape-malay-apricot-chicken"]
  },
  {
    "id":"marinating-penetration-science",
    "term":"Marinating — the Science of Penetration",
    "family":"Flavour infusion · surface chemistry",
    "native":"Latin — marinare, 'to cure in brine'; once preservation, now flavour enhancement",
    "why":"The science: marinades do not deeply penetrate meat — salt moves about 1 cm per hour, oil barely at all, and acid or enzymes affect only the surface. What they actually do: salt denatures proteins (relaxing texture), acid partially hydrolyses collagen (tenderising the surface), and oil carries fat-soluble aromatics. The balance matters: too much acid breaks protein into a mealy mush; too little oil and flavours won't adhere. Overnight is rarely better — 30 min to 2 hours is optimal for most meats.",
    "heritage":"Every culture marinates: South African bobotie and sosaties, Caribbean jerk, Japanese teriyaki, Argentine chimchurri. The braai marinade (peri-peri, garlic, herbs) is a South African obsession.",
    "wisdom":"Butchers and chefs converge: thin cuts need minutes, thick cuts need hours, none need days. The texture tells you — if the surface feels slimy or mushy, the acid has gone too far.",
    "mastery":["Score thick meats to increase surface area for contact.","Balance: acid (1 part), oil (2–3 parts), aromatics (garlic, herbs, spices).","Salt the meat first — it penetrates deeper than the marinade.","Marinate in a non-reactive container (glass, stainless, food-safe plastic).","Pat off excess marinade before cooking — it burns and creates off flavours."],
    "mistakes":["Over-marinating in acid — texture turns to mush, especially fish.","Not scoring thick cuts — flavour stays on the surface.","Marinating in reactive metal (aluminium) — a metallic off taste.","Leaving sugar-heavy marinades too long — they burn before the meat cooks."],
    "metric":"Fish 15–30 min · Chicken 1–2 hr · Beef/lamb 2–4 hr (max) · Vegetables 15–30 min.",
    "requires":{"kit":["non-reactive container","food-safe zip bags or shallow dish","tongs","paper towel"]},
    "dishes":["sosaties","braai-lamb-chops-chimichurri","mozambican-peri-peri-chicken"]
  }
]);
/* register new masterclass ids into the domain map so they appear in the Method Map */
if(window.MC_DOMAIN){Object.assign(window.MC_DOMAIN,{
  'deglazing':'sauces','tempering-eggs':'sauces',
  'mise-en-place':'foundations','acid-brightness':'foundations','toasting-blooming-spices':'foundations',
  'risotto-staged-stock':'water','pasta-al-dente':'water','glazing-vegetables':'water',
  'caramelised-onions':'heat','breading-crumbing':'fat','working-sugar-caramel':'bake',
  'marinating-penetration-science':'cold'
});}
