/* TUB — Cooking methods & culinary terms. Origin + plain-English translation.
   Source: the owner's reference table (verbatim origins/translations), SA-aware (braai).
   cat groups the browsable reference hub. */
window.METHODS = {
  "sauté":{term:"Sauté",origin:"French",plain:"Cook quickly in a little oil over high heat",cat:"stovetop"},
  "pan-fry":{term:"Pan-fry",origin:"English",plain:"Fry in a shallow layer of oil",cat:"stovetop"},
  "deep-fry":{term:"Deep-fry",origin:"English",plain:"Completely immerse in hot oil",cat:"stovetop"},
  "stir-fry":{term:"Stir-fry",origin:"Chinese",plain:"Fry quickly while constantly stirring",cat:"stovetop"},
  "sear":{term:"Sear",origin:"French",plain:"Brown the outside over very high heat",cat:"stovetop"},
  "reverse-sear":{term:"Reverse sear",origin:"Modern",plain:"Slow cook first, then brown at the end",cat:"stovetop"},
  "braise":{term:"Braise",origin:"French",plain:"Brown first, then slow-cook in a little liquid",cat:"stovetop"},
  "stew":{term:"Stew",origin:"English",plain:"Slow-cook completely submerged in liquid",cat:"stovetop"},
  "simmer":{term:"Simmer",origin:"English",plain:"Cook gently below boiling",cat:"stovetop"},
  "boil":{term:"Boil",origin:"English",plain:"Cook in rapidly boiling liquid",cat:"stovetop"},
  "poach":{term:"Poach",origin:"French",plain:"Cook gently in barely simmering liquid",cat:"stovetop"},
  "steam":{term:"Steam",origin:"English",plain:"Cook using steam instead of water",cat:"stovetop"},
  "blanch":{term:"Blanch",origin:"French",plain:"Briefly boil, then cool quickly",cat:"stovetop"},
  "parboil":{term:"Parboil",origin:"English",plain:"Partially boil before finishing another way",cat:"stovetop"},
  "confit":{term:"Confit",origin:"French",plain:"Slowly cook in fat",cat:"stovetop"},
  "sous-vide":{term:"Sous vide",origin:"French",plain:"Vacuum-sealed cooking in temperature-controlled water",cat:"stovetop"},
  "deglaze":{term:"Deglaze",origin:"French",plain:"Add liquid to lift browned bits from a pan",cat:"stovetop"},
  "reduce":{term:"Reduce",origin:"French",plain:"Simmer to evaporate liquid and concentrate flavour",cat:"stovetop"},
  "sweat":{term:"Sweat",origin:"French",plain:"Cook vegetables gently without browning",cat:"stovetop"},
  "scald":{term:"Scald",origin:"English",plain:"Heat milk almost to boiling",cat:"stovetop"},
  "render":{term:"Render",origin:"French",plain:"Melt fat out of meat",cat:"stovetop"},
  "baste":{term:"Baste",origin:"French",plain:"Spoon juices or butter over food while cooking",cat:"stovetop"},
  "roast":{term:"Roast",origin:"English",plain:"Cook uncovered in the oven",cat:"oven"},
  "bake":{term:"Bake",origin:"English",plain:"Cook in the oven (bread, cakes, casseroles)",cat:"oven"},
  "broil":{term:"Broil / Grill (UK)",origin:"English",plain:"Cook under intense direct heat",cat:"oven"},
  "grill":{term:"Grill (US) / Braai (SA)",origin:"English / Afrikaans",plain:"Cook over an open flame",cat:"oven"},
  "char-grill":{term:"Char-grill",origin:"French",plain:"Grill until lightly charred",cat:"oven"},
  "toast":{term:"Toast",origin:"English",plain:"Brown lightly with dry heat",cat:"oven"},
  "smoke":{term:"Smoke",origin:"English",plain:"Cook using wood smoke",cat:"smoke"},
  "cold-smoke":{term:"Cold smoke",origin:"English",plain:"Flavour with smoke without cooking",cat:"smoke"},
  "hot-smoke":{term:"Hot smoke",origin:"English",plain:"Cook while smoking",cat:"smoke"},
  "cure":{term:"Cure",origin:"English",plain:"Preserve with salt and/or sugar",cat:"preserve"},
  "brine":{term:"Brine",origin:"English",plain:"Soak in salted water before cooking",cat:"preserve"},
  "marinate":{term:"Marinate",origin:"French",plain:"Soak in a seasoned liquid to add flavour",cat:"preserve"},
  "pickle":{term:"Pickle",origin:"English",plain:"Preserve in vinegar or brine",cat:"preserve"},
  "ferment":{term:"Ferment",origin:"Latin",plain:"Allow beneficial bacteria or yeast to transform food",cat:"preserve"},
  "emulsify":{term:"Emulsify",origin:"French",plain:"Combine oil and water into a smooth mixture",cat:"mix"},
  "whisk":{term:"Whisk",origin:"English",plain:"Beat ingredients with a whisk",cat:"mix"},
  "fold":{term:"Fold",origin:"French",plain:"Gently combine without losing air",cat:"mix"},
  "beat":{term:"Beat",origin:"English",plain:"Mix vigorously",cat:"mix"},
  "cream":{term:"Cream",origin:"English",plain:"Beat butter and sugar until fluffy",cat:"mix"},
  "knead":{term:"Knead",origin:"English",plain:"Work dough until smooth and elastic",cat:"bake"},
  "proof":{term:"Proof",origin:"English",plain:"Let yeast dough rise",cat:"bake"},
  "shock":{term:"Shock",origin:"Culinary",plain:"Plunge into ice water to stop cooking",cat:"technique"},
  "rest":{term:"Rest",origin:"Culinary",plain:"Let food sit before or after cooking",cat:"technique"},
  "temper":{term:"Temper",origin:"French",plain:"Gradually raise the temperature to avoid curdling",cat:"technique"},
  "clarify":{term:"Clarify",origin:"French",plain:"Remove impurities (or separate butterfat)",cat:"technique"},
  "caramelise":{term:"Caramelise",origin:"French",plain:"Brown sugars until sweet and golden",cat:"finish"},
  "brown":{term:"Brown",origin:"English",plain:"Cook until golden in colour",cat:"finish"},
  "glaze":{term:"Glaze",origin:"French",plain:"Coat with a shiny sauce or finish",cat:"finish"},
  "crisp":{term:"Crisp",origin:"English",plain:"Cook until crunchy",cat:"finish"},
  "julienne":{term:"Julienne",origin:"French",plain:"Cut into thin matchsticks",cat:"prep"},
  "brunoise":{term:"Brunoise",origin:"French",plain:"Very small cubes",cat:"prep"},
  "dice":{term:"Dice",origin:"English",plain:"Medium cubes",cat:"prep"},
  "mince":{term:"Mince",origin:"English",plain:"Chop very finely",cat:"prep"},
  "chiffonade":{term:"Chiffonade",origin:"French",plain:"Thin ribbons (usually herbs or leafy greens)",cat:"prep"},
  "batonnet":{term:"Batonnet",origin:"French",plain:"Thick matchsticks",cat:"prep"},
  "paysanne":{term:"Paysanne",origin:"French",plain:"Thin rustic slices",cat:"prep"},
  "rondelle":{term:"Rondelle",origin:"French",plain:"Round slices",cat:"prep"},
  "butterfly":{term:"Butterfly",origin:"English",plain:"Slice almost through and open flat",cat:"prep"},
  "spatchcock":{term:"Spatchcock",origin:"Irish / English",plain:"Remove backbone and flatten poultry",cat:"prep"}
};
window.METHOD_CATS={
  stovetop:"On the stove",oven:"In the oven & over fire",smoke:"Smoke",
  preserve:"Preserve & cure",mix:"Mix & combine",bake:"Dough & baking",
  technique:"Technique",finish:"Finish & glaze",prep:"Knife & prep"
};
