/* Generate sw.js: precache the app shell + every recipe module for full offline,
   network-first navigation (freshness), stale-while-revalidate for same-origin
   assets, cache-first for cross-origin (fonts). Bump VERSION on content changes. */
const fs=require('fs');
const recipeFiles=fs.readdirSync('recipes').filter(f=>/\.js$/.test(f)).map(f=>'./recipes/'+f);
const PRECACHE=['./tub-app.html','./manifest.webmanifest','./icon-192.png','./icon-512.png'].concat(recipeFiles);
const VERSION='tub-v1';
const sw=`/* TUB service worker — auto-generated by build-pwa.js. Do not edit by hand. */
const CACHE='${VERSION}';
const PRECACHE=${JSON.stringify(PRECACHE)};
self.addEventListener('install',e=>{e.waitUntil((async()=>{const c=await caches.open(CACHE);await c.addAll(PRECACHE);await self.skipWaiting();})());});
self.addEventListener('activate',e=>{e.waitUntil((async()=>{const ks=await caches.keys();await Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim();})());});
self.addEventListener('fetch',e=>{
  const req=e.request; if(req.method!=='GET') return;
  const url=new URL(req.url);
  if(req.mode==='navigate'){
    e.respondWith(fetch(req).then(r=>{const cp=r.clone();caches.open(CACHE).then(c=>c.put(req,cp));return r;}).catch(()=>caches.match(req)));
    return;
  }
  if(url.origin!==location.origin){
    e.respondWith(caches.match(req).then(c=>c||fetch(req).then(r=>{const cp=r.clone();caches.open(CACHE).then(cc=>cc.put(req,cp));return r;}).catch(()=>c)));
    return;
  }
  e.respondWith(caches.match(req).then(c=>{const net=fetch(req).then(r=>{const cp=r.clone();caches.open(CACHE).then(cc=>cc.put(req,cp));return r;}).catch(()=>c);return c||net;}));
});
`;
fs.writeFileSync('sw.js',sw);
console.log('sw.js written: '+PRECACHE.length+' precache entries (version '+VERSION+')');
