/* Classify all 146 dishes for review: meal vs non-meal, + flag duplicates.
   Outputs RECIPE_REVIEW.md grouped by category. */
const fs=require('fs'),D='/Users/brandondienar/.claude/jobs/d2505485/tmp/';
const atlas=require('./recipe-atlas.json');
// category codes: MAIN, SOUP, BRUNCH, STARTER, BREAD, STARCH, SWEET, SNACK, COND, DRINK
const CAT={
  mussakhan:['MAIN','Chicken-on-taboon-bread, Palestinian main'],
  kibbeh:['MAIN','Bulgur-&-meat croquettes, Levantine main'],
  fattoush:['STARTER','Salad'],
  'palak-paneer':['MAIN','Curry main'],
  'malai-kofta':['MAIN','Curry main'],
  potjiekos:['MAIN','Stew main'],
  melktert:['SWEET','Dessert (milk tart)'],
  koeksisters:['SWEET','Sweet (syrup doughnut)'],
  vetkoek:['MAIN','Filled fried bread = a meal (has curried mince)'],
  potbrood:['BREAD','Bread (side)'],
  chakalaka:['COND','Relish / side'],
  focaccia:['BREAD','Bread (side)'],
  'sticky-toffee-pudding':['SWEET','Dessert'],
  borscht:['SOUP','Soup (eaten as a meal)'],
  crepes:['BRUNCH','Sweet/savoury crêpes — breakfast/dessert'],
  'coq-au-vin':['MAIN','Braise main'],
  'rogan-josh':['MAIN','Curry main'],
  'lamb-shank-red-wine':['MAIN','Braise main'],
  'french-onion-soup':['SOUP','Soup (meal)'],
  'steak-frites-cafe-de-paris':['MAIN','Steak main'],
  bouillabaisse:['SOUP','Stew-soup (meal)'],
  'duck-a-l-orange':['MAIN','Roast main'],
  'beef-wellington':['MAIN','Pastry main'],
  'chicken-tikka-masala':['MAIN','Curry main'],
  bibimbap:['MAIN','Rice bowl main'],
  'macaroni-cheese':['MAIN','Pasta bake main'],
  'chicken-satay':['STARTER','Skewers (starter; main with rice)'],
  'dan-dan-noodles':['MAIN','Noodle main'],
  'tom-yum-goong':['SOUP','Soup (starter/light meal)'],
  'banh-mi':['MAIN','Sandwich main'],
  tteokbokki:['SNACK','Street snack'],
  'char-siu-pork':['MAIN','Roast pork main (with rice)'],
  'bunny-chow':['MAIN','Curry-in-bread main'],
  'durban-mutton-curry':['MAIN','Curry main'],
  boerewors:['MAIN','Braai sausage (main with pap)'],
  'shisa-nyama':['MAIN','Braai feast main'],
  'mozambican-peri-peri-chicken':['MAIN','Grilled chicken main'],
  'waterblommetjie-bredie':['MAIN','Stew main'],
  denningvleis:['MAIN','Stew main'],
  sosaties:['STARTER','Skewers (braai starter/main)'],
  'snoek-braai-apricot-jam':['MAIN','Fish main'],
  umngqusho:['STARCH','Samp & beans — side (or veg main)'],
  breyani:['MAIN','Rice main'],
  'pickled-fish':['MAIN','Cape Malay fish main'],
  pap:['STARCH','Starch side (mealie-meal porridge)'],
  roosterkoek:['BREAD','Braai bread (side)'],
  'mealie-bread':['BREAD','Bread (side)'],
  biltong:['SNACK','Cured meat snack — NOT a meal'],
  droewors:['SNACK','Cured sausage snack — NOT a meal'],
  'peppermint-crisp-tart':['SWEET','Dessert'],
  hertzoggies:['SWEET','Biscuit/tart (sweet)'],
  'linguine-vongole-clams':['MAIN','Pasta main'],
  'braai-lamb-chops-chimichurri':['MAIN','Grilled chops main'],
  'roast-leg-lamb-rosemary-garlic':['MAIN','Roast main'],
  'pappardelle-venison-wild-mushroom-ragu':['MAIN','Pasta main'],
  'arroz-negro-black-paella':['MAIN','Rice main'],
  'red-wine-braised-short-rib':['MAIN','Braise main'],
  'oysters-mignonette':['STARTER','Starter (not a meal)'],
  'steak-tartare':['STARTER','Starter (main in France)'],
  'whole-roast-sea-bass':['MAIN','Fish main'],
  'naan-bread':['BREAD','Bread (side)'],
  guacamole:['COND','Dip / condiment'],
  'elote-mexican-street-corn':['SIDE_SNACK','Street corn side/snack'],
  croissants:['BREAD','Viennoiserie (breakfast)'],
  'flapjacks-pancakes':['BRUNCH','Breakfast/brunch'],
  'eggs-benedict-hollandaise':['BRUNCH','Breakfast main'],
  quesadillas:['STARTER','Snack/light main'],
  'gemista-stuffed-peppers-aubergine':['MAIN','Stuffed-veg main'],
  pozole:['SOUP','Stew-soup (meal)'],
  tamales:['MAIN','Mesoamerican main'],
  'harira-lamb-chickpea-soup':['SOUP','Soup (meal)'],
  'causa-limena':['STARTER','Peruvian potato starter'],
  'beef-teriyaki':['MAIN','Main (with rice)'],
  'chicken-biryani':['MAIN','Rice main'],
  'southern-fried-chicken':['MAIN','Chicken main'],
  'lasagne-bolognese':['MAIN','Pasta bake main'],
  'quiche-lorraine':['BRUNCH','Egg tart — lunch/brunch main'],
  'falafel-plate':['MAIN','Mezze main (with bread)'],
  'bun-cha':['MAIN','Grilled pork + noodles main'],
  'korean-fried-chicken':['STARTER','Snack/main (with sides)'],
  'doro-wat':['MAIN','Ethiopian stew main'],
  tiramisu:['SWEET','Dessert'],
  'creme-brulee':['SWEET','Dessert'],
  'malva-pudding':['SWEET','Dessert'],
  'mango-sticky-rice':['SWEET','Dessert'],
  'chicken-liver-parfait':['STARTER','Starter (pâté)'],
  spanakopita:['STARTER','Pie (starter or veg main)'],
  'lamb-tagine-apricot-almond':['MAIN','Tagine main'],
  gatsby:['MAIN','SANDWICH FEAST main'],
  braaibroodjie:['BRUNCH','Braai toasted sandwich (light meal)'],
  frikkadels:['MAIN','Meatballs (main with sides)'],
  tamatiebredie:['MAIN','Stew main'],
  geelrys:['STARCH','Yellow rice — side'],
  dombolo:['STARCH','Steamed bread dumplings — side'],
  magwinya:['SNACK','Fat-cake snack / street'],
  morogo:['SIDE','Stewed greens — side'],
  skilpadjies:['STARTER','Liver-wrapped braai bites'],
  mosbolletjies:['SWEET','Sweet buns'],
  pampoenkoekies:['SIDE_SNACK','Pumpkin fritters — side/sweet'],
  boeber:['DRINK','Milk drink'],
  'buttermilk-rusks':['SNACK','Rusks — snack'],
  atchar:['COND','Pickle / condiment'],
  umqombothi:['DRINK','Traditional beer'],
  'dom-pedro':['DRINK','Milk-liqueur drink'],
  kaiings:['SIDE','Pork crackling bits — side/traditional'],
  umphokoqo:['STARCH','Crumbly pap — side'],
  isidudu:['BRUNCH','Pumpkin porridge — breakfast'],
  amadumbe:['STARCH','Yam — starch side'],
  'oxtail-potjie':['MAIN','Stew main'],
  'vetkoek-curry-mince':['DUP','DUPLICATE of "vetkoek"'],
  'putu-pap':['DUP','Krummelpap — overlaps pap / umphokoqo'],
  'moroho-sotho':['DUP','Overlaps morogo (stewed greens)'],
  'potato-bredie':['MAIN','Stew main'],
  'cape-malay-apricot-chicken':['MAIN','Stew main'],
  'mozambican-prawns':['MAIN','Prawn main'],
  'fish-and-chips':['MAIN','Fried fish main'],
  'shepherds-pie':['MAIN','Pie main'],
  'cottage-pie':['MAIN','Pie main'],
  'chicken-pot-pie':['MAIN','Pie main'],
  'chicken-noodle-soup':['SOUP','Soup (meal)'],
  'cream-of-tomato-soup':['SOUP','Soup (light meal/side)'],
  'garlic-bread':['BREAD','Bread (side)'],
  bruschetta:['STARTER','Toast starter'],
  'caprese-salad':['STARTER','Salad'],
  'caesar-salad':['STARTER','Salad'],
  nachos:['STARTER','Snack/sharing starter'],
  'chicken-wings':['SNACK','Snack/sharing'],
  'pulled-pork':['MAIN','Sandwich/main'],
  meatloaf:['MAIN','Main'],
  'roast-beef':['MAIN','Roast main'],
  'sausage-rolls':['SNACK','Baked snack'],
  frittata:['BRUNCH','Egg main (lunch/brunch)'],
  'french-toast':['BRUNCH','Breakfast'],
  waffles:['BRUNCH','Breakfast'],
  'ceviche-classico':['STARTER','Raw-fish starter (main in Peru)'],
  xiaolongbao:['STARTER','Soup dumplings (meal-ish)'],
  okonomiyaki:['MAIN','Savoury pancake main'],
  yakitori:['SNACK','Skewers snack'],
  takoyaki:['SNACK','Octopus balls snack'],
  'banh-xeo':['MAIN','Crêpe main'],
  'laarb-mince':['STARTER','Minced-meat salad (main in SE Asia)'],
  'nasi-lemak':['MAIN','Rice plate main'],
  'laksa-curry':['MAIN','Noodle soup main'],
  'taiwanese-beef-noodle-soup':['MAIN','Noodle soup main'],
  jianbing:['BRUNCH','Street breakfast crêpe'],
  khachapuri:['MAIN','Cheese-bread main']
};
const ORDER=[
  ['MAIN','🍽️ Proper meals (mains)','These are full dinner mains — the core of the book.'],
  ['SOUP','🥣 Soups & stews','Full bowl-meals.'],
  ['BRUNCH','🍳 Breakfast & brunch','Meals (just not dinner).'],
  ['STARTER','🥗 Starters, salads & small plates','Not a full meal on their own — keep as starters or prune.'],
  ['STARCH','🍚 Starch sides','Sides, not meals (best folded into the dishes they accompany).'],
  ['BREAD','🍞 Breads & baked goods','Sides/breakfast, not meals.'],
  ['SWEET','🧁 Desserts & sweets','Not meals.'],
  ['SNACK','🥨 Snacks, cured & sharing','Snacks — not meals.'],
  ['SIDE','🥬 Vegetable / other sides','Sides, not meals.'],
  ['SIDE_SNACK','🧂 Sides that read as snacks',''],
  ['COND','🫙 Condiments, relishes & dips','Accompaniments, not meals.'],
  ['DRINK','🥤 Drinks','Beverages, not meals.'],
  ['DUP','🔁 Likely duplicates','Two roster entries for the same dish — consolidate.']
];
const MEAL=new Set(['MAIN','SOUP','BRUNCH']);
let lines=['# TUB — Recipe Selection Review','','**Total roster:** '+Object.keys(atlas).length+' dishes.  ','Classified by whether each is a proper **meal** or something else (dessert, bread, side, snack, condiment, drink), plus likely duplicates.','','> Mark anything you want **pruned** (removed), **merged**, or **kept** — or just tell me "drop all non-meals" and I\'ll action it. Anything tagged below is my read; your call overrides.',''];
// counts
const byCat={};Object.values(CAT).forEach(c=>{byCat[c[0]]=(byCat[c[0]]||0)+1;});
let meals=0,nonmeals=0;Object.entries(CAT).forEach(([s,c])=>{if(MEAL.has(c[0]))meals++;else nonmeals++;});
lines.push('## Summary');lines.push('');
lines.push('- **Proper meals (mains/soups/brunch):** '+meals);
lines.push('- **Non-meals (everything else):** '+nonmeals);
lines.push('- **Likely duplicates:** '+(byCat['DUP']||0));
lines.push('');
ORDER.forEach(([code,title,sub])=>{
  const items=Object.entries(CAT).filter(([s,c])=>c[0]===code);
  if(!items.length)return;
  lines.push('## '+title+'  ('+items.length+')');
  if(sub)lines.push('*'+sub+'*');lines.push('');
  lines.push('| # | Dish | Cuisine | Tier | Note |');
  lines.push('|---|------|---------|------|------|');
  items.sort((a,b)=>(atlas[a[0]].tier||'').localeCompare(atlas[b[0]].tier||'')||atlas[a[0]].t.localeCompare(atlas[b[0]].t));
  items.forEach(([s,c],i)=>{const d=atlas[s];lines.push('| '+(i+1)+' | **'+d.t+'** `'+s+'` | '+(d.cui||'')+' | '+d.tier+' | '+c[1]+' |');});
  lines.push('');
});
fs.writeFileSync(D+'RECIPE_REVIEW.md',lines.join('\n'));
console.log('wrote RECIPE_REVIEW.md | meals='+meals+' non-meals='+nonmeals+' dups='+(byCat['DUP']||0));
console.log('\nby category:');
Object.entries(byCat).sort((a,b)=>b[1]-a[1]).forEach(([c,n])=>console.log('  '+c.padEnd(12)+n));
